### ISSUE TITLE
Use serializers for views

### ISSUE THREAD

**Issue by denizdogan** [wagnerdelima/drf-social-oauth2#104]
It would be nice if there were DRF serializers for the various token views so that it would be easier to see exactly what is expected from the client side. This could also help with generating the OpenAPI spec, using drf-spectacular.

**Comment by wagnerdelima** [comment]
Hi @denizdogan.

I will keep this in mind. I may work on it soon, actually. Thank you for your sugestion.

**Comment by denizdogan** [comment]
@wagnerdelima Thanks. I don't use Django in general anymore, so unfortunately I won't be able to assist here.

**Comment by wagnerdelima** [comment]
@denizdogan that's alright. The idea is still valid.
