### ISSUE TITLE
Get new acess token

### ISSUE THREAD

**Issue by pear9** [wagnerdelima/drf-social-oauth2#107]
What is the URL to get new **access token** by providing **refresh token**.
I found out only new **refresh token** can be generated by previous **refresh token**.

**Comment by wagnerdelima** [comment]
So far this endpoint doesn't exist. It should be implemented in the future. You can send another /convert-token request and get another access token. If you use the latest version 1.2.0, there will be no duplicate valid access tokens in your database, therefore saving space.

**Comment by pear9** [comment]
can you please provide a little more detail of URL and what is the body parameters plus headers

**Comment by wagnerdelima** [comment]
You can get more details from the readme file, specifically this paragraph:
https://github.com/wagnerdelima/drf-social-oauth2#testing-the-setup.

Also, you can launch the oas swagger and get even more detais:
https://github.com/wagnerdelima/drf-social-oauth2#run-swagger-editor

**Comment by krishnanpandya007** [comment]
> So far this endpoint doesn't exist. It should be implemented in the future. You can send another /convert-token request and get another access token. If you use the latest version 1.2.0, there will be no duplicate valid access tokens in your database, therefore saving space.

So what if we saved refresh token and access token only on client side and if access token expires isnt't that possible to get new access token based upon refresh token? 

i've tried using url ```localhost:8000/auth/token``` passing values like ```refresh_token, grant_type, client_id etc...``` but it generated new access token as well as new refresh token

**Comment by wagnerdelima** [comment]
@krishnanpandya007 yes, as it is a new access token and refresh tokens will be generated.  You will have to sign in again.
