### ISSUE TITLE
Changing the auth token header 'Bearer' to a custom header?

### ISSUE THREAD

**Issue by thesealednectar22** [wagnerdelima/drf-social-oauth2#114]
Could you please direct me to how to change the default auth token header 'Bearer' to a custom header? Thank you

**Comment by denizdogan** [comment]
It probably would not be simple, as "Bearer" is pretty hardcoded. Maybe your best bet is to rewrite all request headers before this library starts processing them.

**Comment by wagnerdelima** [comment]
Please, give me more context on what you need to do here. Thanks.

**Comment by wagnerdelima** [comment]
I am closing this issue due to a lack of context.
