### ISSUE TITLE
Proper error handling required

### ISSUE THREAD

**Issue by Chappie74** [wagnerdelima/drf-social-oauth2#117]
**Describe the bug**
An error is thrown when trying to get a new access token using `refresh_token` grant of a revoked token. 

**To Reproduce**
1. Authenticate using `/auth/token` (`password` grant), get a `refresh_token` and an `access_token` 
2. Revoke the access token using `auth/revoke-token`.
3. With the refresh token generated in 1. , try to get a new access token using `/auth/token` (`refresh_token` grant)
4.  This will throw 500 error, `oauth2_provider.models.AccessToken.DoesNotExist: AccessToken matching query does not exist.`

**Expected behavior**
I expect the error to be handled silently, and a probably return 400 status code, with message `invalid grant`. 

**Screenshots**
![image](https://user-images.githubusercontent.com/21108487/153693344-57b99e43-4bbd-4709-a1a8-cecdb56ea06e.png)

**Comment by wagnerdelima** [comment]
@Chappie74 maybe you could upload your code somewhere and I could replicate from your repo?
