### ISSUE TITLE
"Select a valid choice" error while creating application

### ISSUE THREAD

**Issue by xennygrimmato** [wagnerdelima/drf-social-oauth2#119]
I followed the steps in the README file to setup drf-social-oauth2.
While creating an Application in the admin panel, I get a "Select a valid choice" error even though I'm supplying the  correct superuser username.

<img width="624" alt="Screenshot 2022-02-17 at 6 32 35 PM" src="https://user-images.githubusercontent.com/4271899/154487414-8d1d1f31-4b65-449d-9f7b-f60554cdcfc0.png">

**Comment by wagnerdelima** [comment]
The user shall not be typed in the system. Instead, you need to select it from a button that appears right next to the user text.
