### ISSUE TITLE
Authorization By `Bearer` not working 

### ISSUE THREAD

**Issue by krishnanpandya007** [wagnerdelima/drf-social-oauth2#124]
As working on some protected backend views i have some views covered by ```permissions.IsAuthenticated``` which is only allow known users to hit this endpoint

As going to your quick manual
![image](https://user-images.githubusercontent.com/96008120/165266599-b98a2666-285d-437d-9895-a7d35953a61b.png)

i replaced ```<backend_name>``` with my custom backend name and ```<backend_token>``` by an access_token which is been generated by it-self but however when i try to hit protected endpoint i got error saying

```error
{"detail":"Authentication credentials were not provided."}
```

**Comment by wagnerdelima** [comment]
Are you sure you have the correct token? 

![image](https://user-images.githubusercontent.com/7796148/165332538-8907e12b-6852-4e8b-a51c-8cba392eed36.png)

I am using postman and I can post successfully.

**Comment by krishnanpandya007** [comment]
> Are you sure you have the correct token?
> 
> ![image](https://user-images.githubusercontent.com/7796148/165332538-8907e12b-6852-4e8b-a51c-8cba392eed36.png)
> 
> I am using postman and I can post successfully.

I take access token from admin panel  {Access Tokens} section and it's not expired yet

Am I doing or taking wrong token?

**Comment by wagnerdelima** [comment]
Let's go step by step. First you need to fire a request to the /convert-token endpoint. That will respond with a response that includes your access token. You're going to copy that token and include it to the Bearer <token you just copied>. Are you doing that?

**Comment by krishnanpandya007** [comment]
> Let's go step by step. First you need to fire a request to the /convert-token endpoint. That will respond with a response that includes your access token. You're going to copy that token and include it to the Bearer . Are you doing that?

I am getting the access_token from localhost:8000/auth/token/ as i am getting this token from credentials details. I hope this also works. but still it's unAuthorized can u imagine any core cases (anything that affect)??

**Comment by wagnerdelima** [comment]
Do not get the token from auth/token, but from auth/convert-token.

**Comment by krishnanpandya007** [comment]
for credentials sign in, what should be my ```backend``` parameter (the name of manually created apk. giving error 'Invalid Backend Parameter') and ```token``` parameter to hit endpoint ```auth/convert-token```

**Comment by krishnanpandya007** [comment]
> Do not get the token from auth/token, but from auth/convert-token.

Any way i can get list of those tokens which are valid in ```Authorization``` header?

**Comment by krishnanpandya007** [comment]
Hey, finally works but only when i specifically specify the access token in Authorization section in postman

But when i put ```Bearer access_token``` as value of Authorization header its not working as it works on simple rest_framework authentication 

Thx for hearing me out!

**Comment by krishnanpandya007** [comment]
Nope, this token also not working however Basic Authentication works fine as providing username and password, but no tokens working on protected routes with Bearer

**Comment by krishnanpandya007** [comment]
Looks like configurations gone wrong at settings.py

Working now!!!

**Comment by dimnik97** [comment]
Hi! I faced the same problem. Send request with the token I've got from auth/convert-token, but get the same error. What could be wrong?
<img width="765" alt="image" src="https://user-images.githubusercontent.com/32041486/203347448-7c961655-9926-4d89-8d9f-91142b90aa80.png">
