### ISSUE TITLE
oauthlib.oauth2.rfc6749.errors.InvalidClientIdError: (invalid_request) <....SANITIZED> when i'm using Django>=4.0.4

### ISSUE THREAD

**Issue by anusikh** [wagnerdelima/drf-social-oauth2#126]
I followed the README to get this package working on Django>=4.0.4 and created an application as mentioned in the django-oauth-toolkit section, but when im trying to use social authentication, it gives the above error. The jwt authentication is working just fine though .

**Comment by wagnerdelima** [comment]
This is impossible to reproduce, there are no instructions, steps, docs, images etc.
