### ISSUE TITLE
oauthlib.oauth2.rfc6749.errors.InvalidClientError in google OAuth

### ISSUE THREAD

**Issue by simo-berto98** [wagnerdelima/drf-social-oauth2#129]
hi, i'm trying to set up authentication with google but the library throws me an InvalidClientError exception calling the auth / convert-token service.
As per documentation, I entered the values self-generated by django admin in the client_id and client_secret parameters.
What can be the problem? My configuration error?

![image](https://user-images.githubusercontent.com/38985338/171998396-ab2b65e9-6d3b-4ed3-8760-835a009366b2.png)

**Comment by wagnerdelima** [comment]
Hi @simo-berto98.
Please, see if this https://github.com/wagnerdelima/drf-social-oauth2/issues/38 helps you.

**Comment by wagnerdelima** [comment]
@simo-berto98 can you try the newest versions of drf-social-oauth2? I believe this might be solved. Otherwise, please follow the standard way of create issues, explaining how to replicate it.

Thanks.
