### ISSUE TITLE
New columns added in UserSocialAuth for dependency social-auth-app-django 3.2.0

### ISSUE THREAD

**Issue by michaellin86** [wagnerdelima/drf-social-oauth2#13]
The issue is based off of the original repo, but the owner seemed to have stopped maintaining it. Adding issue here instead.

Basically I was using django-rest-framework-social-oauth2 for Google OAuth2, and starting about early June I started getting this error:

```
ProgrammingError
column social_auth_usersocialauth.created does not exist
LINE 1: ..."uid", "social_auth_usersocialauth"."extra_data", "social_au...
                                                             ^
```

Some investigation led me to realize that the dependency **social_auth_usersocialauth v3.2.0** added two new columns to the UserSocialAuth model, namely **created** and **modified**. However, the requirements for this allows >=3.1.0, which hid the breaking change. Partly was my fault for not realizing my app updated to a newer version of social_auth_usersocialauth, but would be nice if future releases can pin specific versions of dependencies.

**Comment by wagnerdelima** [comment]
Hey @michaellin86. Thanks for investigating that out. Tagging specific versions of dependencies may be achieved via tagging. This project has just started to be maintained by me. So, you could actually just run python manage.py migrate on your project and you should have gotten this issue resolved. 

Btw, what did you do to get this error? Did Google OAuth2 use a higher version of social_auth_usersocialauth?

I will update the dependencies to the newest. Thanks.

**Comment by michaellin86** [comment]
> Hey @michaellin86. Thanks for investigating that out. Tagging specific versions of dependencies may be achieved via tagging. This project has just started to be maintained by me. So, you could actually just run python manage.py migrate on your project and you should have gotten this issue resolved.
> 
> Btw, what did you do to get this error? Did Google OAuth2 use a higher version of social_auth_usersocialauth?
> 
> I will update the dependencies to the newest. Thanks.

Sorry for the late reply. I think what happened was when I rebuilt my production Docker image, it installed **django-rest-framework-social-oauth2** and then looked for the latest available version of **social_auth_usersocialauth** >= v3.1.0, which would have probably been v3.2.0 or v4.0.0. But in my local development environment, I already had social_auth_usersocialauth v3.1.0 installed so that was the version used, and nothing happened when I did a migration against the production database. I probably should've done a better job keeping my prod and local environment consistent. But thanks for looking into this!

**Comment by wagnerdelima** [comment]
My pleasure. Thanks for using the framework. :)
