### ISSUE TITLE
InvalidClientError at /auth/convert-token (invalid_client)  <oauthlib.Request SANITIZED>

### ISSUE THREAD

**Issue by shukhrat121995** [wagnerdelima/drf-social-oauth2#133]
**Describe the bug**
Retrieved token from Google cannot be converted

**To Reproduce**
1. Go to OAuth 2.0 Playground
2. Select Google OAuth2 API v2 and authorize https://www.googleapis.com/auth/userinfo.email
https://www.googleapis.com/auth/userinfo.profile
3. Exchange Authorization code for tokens and get access token
4. Use this token in convert-token 

**Expected behavior**
/auth/convert-token has to return access token and refresh token

**Screenshots**

**Desktop (please complete the following information):**
 - Browser [ chrome ]

**Additional context**
Django version 4.0.5

**Comment by shukhrat121995** [comment]
I got it working. Why you didn't mention setting up the application? It is different from what you mentioned. I found this article https://djangokatya.com/2021/04/09/social-login-for-django-rest-framefork-for-newbies-a-k-a-for-me/ hope it will be useful for others

**Comment by ehsanbarkhordar** [comment]
I have the same issue and I do not know how I should fix it?
