### ISSUE TITLE
compatibility issue with django-oauth-toolkit==2.1.0

### ISSUE THREAD

**Issue by ehsan-g** [wagnerdelima/drf-social-oauth2#135]
I am keep getting the "invalid client error" when I had django-oauth-toolkit==2.1.0 installed.
I had to change it  to django-oauth-toolkit==1.3.2

**Comment by babor99** [comment]
what version of django and drf did you use?

**Comment by ehsan-g** [comment]
I think I didn't change django version - Django==3.2.14

**Comment by wagnerdelima** [comment]
I had some time to investigate this. Indeed, it does not work with django oauth toolkit equal or above 2.0.0. Reason is the new check_password(client_secret, request.client.client_secret) condition added in oauth2_providers/oauth2_validators, line 180. It is a bug on the password hasher.

**Comment by shrivardha** [comment]
@ehsan-g how did u change the version of django-oauth-toolkit?

**Comment by ehsan-g** [comment]
@shrivardha 
`django-environ==0.9.0
# django-oauth-toolkit==2.1.0 // compability issue with social auth
django-oauth-toolkit==1.3.2
djangorestframework==3.12.4
drf-social-oauth2==1.2.1
social-auth-app-django==5.0.0
social-auth-core==4.3.0`
