### ISSUE TITLE
Google oauth2

### ISSUE THREAD

**Issue by PrasanthPerumalsamy** [wagnerdelima/drf-social-oauth2#138]
**google oauth2 not providing access tokens for newly created id's only providing id_token**

here is the link https://developers.google.com/identity/sign-in/web/backend-auth

Please update the package...

**Comment by SukiCZ** [comment]
Hi @PrasanthPerumalsamy 
I was facing same issue and fixed that with a custom Backend that inherits from `GooglePlusAuth`.

```py
from social_core.backends.google import GooglePlusAuth


class GoogleIdentityBackend(GooglePlusAuth):
    name = "google-identity"

    def user_data(self, access_token, *args, **kwargs):
        """Don't care about the `id_token`"""
        response = self.get_json(
            # https://oauth2.googleapis.com/tokeninfo
            "https://www.googleapis.com/oauth2/v3/tokeninfo",
            params={"id_token": access_token},
        )
        self.process_error(response)
        return response

```

I believe this issue is more related to [python-social-core](https://github.com/python-social-auth/social-core)

**Comment by MehdiDRISSIB** [comment]
I got the same issue. google provide only id_token and no longuer accesstoken  Any help please

**Comment by SukiCZ** [comment]
@MehdiDRISSIB Have you tried customize the `GooglePlusAuth`? The customization I'd posted works for me.

**Comment by MehdiDRISSIB** [comment]
@SukiCZ Many thanks for your feedback. As I use Facebook login also in my app, I would like keep the same api for both.
If it's not fixed in the package, yes I would have to go through another way and probably try your view. I will give a feedback if I try your solution

**Comment by wagnerdelima** [comment]
Hi guys. I didn't understand the problem per se. I will close this issue and you can create another based on a template that makes it easier to understand. 

Thanks.
