### ISSUE TITLE
How to use in conjunction with another auth scheme?

### ISSUE THREAD

**Issue by nicleary** [wagnerdelima/drf-social-oauth2#139]
I'm trying to use drf-social-oauth2 (specifically with Github OAuth) and would like to also allow for drf's native Token authentication. Are there any examples of this?

I've attempted to complete the setup of this, and authentication works great when logging in with the github oauth flow. However, after I create a token for a user, and attempt to authenticate using that, I receive an error of

```json
{
    "detail": "Invalid token header. Invalid backend."
}
```

DRF's token auth doesn't appear to provide an authentication backend. What would be the best solution in this case?

**Comment by wagnerdelima** [comment]
I need more details on this. What have you tried, replication methods etc.

**Comment by wagnerdelima** [comment]
I am closing this issue due to the lack of details. If you decide to reinvestigate the issue, please reopen it.
