### ISSUE TITLE
Please publish this package to pypi

### ISSUE THREAD

**Issue by jperelli** [wagnerdelima/drf-social-oauth2#14]
:)
How can I help to make it happen? do you need a setup.py or something? Maybe I can publish and then transfer ownership to you. I'll investigate

**Comment by wagnerdelima** [comment]
It's been already published. 
https://pypi.org/project/drf-social-oauth2/

**Comment by jperelli** [comment]
Cool, this confused me https://github.com/wagnerdelima/drf-social-oauth2/pull/15
