### ISSUE TITLE
401 Error (Unauthorized) and Uncaught (in promise) Error: Request failed with status code 401 on browser.

### ISSUE THREAD

**Issue by Madhu25666** [wagnerdelima/drf-social-oauth2#141]
**We seem to be getting a 401 error with the new django admin with drf social oauth2.  But working fine on Postman **
We are getting a 401 Error (Unauthorized) when we pass the clientid and client_secret through browser. The same clientID and secret returns the tokens on PostMan.

**To Reproduce**
1. Go to Login page where the signin button is'
2. Click on 'Signin'
3. Scroll down to 'Console'
4. POST http://127.0.0.1:8000/auth/token/ 401 (Unauthorized) and Uncaught (in promise) Error: Request failed with status code 401

**Expected behavior**
An object with access and refresh token

**Screenshots**
![error1](https://user-images.githubusercontent.com/20838739/197991047-25723fba-55b1-44bd-b099-54bce8d740f8.PNG)
![error2](https://user-images.githubusercontent.com/20838739/197991062-11cace2d-d2f9-4737-b70d-675506a48c07.PNG)
![error3](https://user-images.githubusercontent.com/20838739/197991076-2bb64495-f1d6-41c2-8a5a-d25a9b2deb22.PNG)
![error4](https://user-images.githubusercontent.com/20838739/197991310-217a7a05-f843-4b5a-be42-d921d94ed466.PNG)

**Desktop (please complete the following information):**
 - Windows 10 Pro]
 - [Chrome]
 
**Additional context**
This was working perfectly before the update to Django administration .

**Comment by merwan32** [comment]
hi , I have same probleme do you solved ??
tell me ,

**Comment by wagnerdelima** [comment]
If it's working fine on Postman, you have an issue with your front-end application.
One question, @Madhu25666 why are you authenticating with /token and not /convert-token?
