### ISSUE TITLE
Customised User Model with 'email' as USERNAME_FIELD

### ISSUE THREAD

**Issue by lucaleoni73** [wagnerdelima/drf-social-oauth2#150]
I'm working with drf-social-oauth2 to implement both social login and credentials login. I customised the UserModel by removing the username and specifying the email field inside USERNAME_FIELD. I also customised the UserManager and the auth_back (extending from ModelBackend). Still when I try to call `/token ` to generate a new set of token I receive back the response saying that the Request is missing the username parameter. How to do I change this parameter to set it as the email?

**Comment by wagnerdelima** [comment]
Unfortunately, I can't help you given that this is not an issue with drf-social-oauth2. I do not have a way to reproduce it. 
Why are you calling /token and not /convert-token?
