### ISSUE TITLE
What are  SOCIAL_AUTH_GOOGLE_OAUTH2_KEY and SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET?

### ISSUE THREAD

**Issue by tungvv318** [wagnerdelima/drf-social-oauth2#151]
I'm a newbie with drf-social-oauth2. I have questions likes:

1, SOCIAL_AUTH_GOOGLE_OAUTH2_KEY and SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET is client_id and client_sercet in google console and is client_id and client_secret in frontend passing for backend? What are the purposes of its in the application?

2, from what I read in the code looks like the client_id and client_secret that the frontend sends to the backend just need to be the same as the client_id and client_secret in the Application table?

Note: same question with the bro in [link stackoverflow
](https://stackoverflow.com/questions/68789367/some-settings-seem-useless-in-drf-social-oauth2)

**Comment by wagnerdelima** [comment]
I have written instructions on how to proceed with google here: https://github.com/wagnerdelima/drf-social-oauth2#google-example. 

Good luck.
