### ISSUE TITLE
Getting error while the user is disabled(is_active=False)

### ISSUE THREAD

**Issue by PankajSavaliya** [wagnerdelima/drf-social-oauth2#18]
works perfectly While users login with the Facebook first time. in some cases, admin can disable the users(**is_active=False**).

Users can't log in with Facebook after disabling by admin. getting error **NoneType**

```
[Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 
'NoneType'>`](url)
```

**Comment by wagnerdelima** [comment]
Can you be more specific? Where exactly are you setting this is_active to False? How is this framework being used by you?

**Comment by wagnerdelima** [comment]
A user should not be able to log in if they are disabled by admins. It is a security procedure used instead of deleting users.

**Comment by PankajSavaliya** [comment]
This is not a reliable answer from your side, it should raise an error with the proper message but right now getting an error, and this error is not generating a proper message

**Comment by wagnerdelima** [comment]
Ok so let's think this through. You have a user that should log in to something of yours. Then the admin for some reason disabled the user and you can't log in anymore. mmm.... Yes this is a completely reliable answer from my side. 
In fact what's not reliable is this restriction you actually want to bypass.

**Comment by PankajSavaliya** [comment]
That's absolutely true if the user is disabled then it won't go inside.
in my case, getting an exception error NoneType with 500 code, but your library should give a message like

>  this user is disabled 

with 400 Bad request.

**Comment by wagnerdelima** [comment]
Look I will investigate this further. But you can always open a PR with the fix. Easy peasy.

**Comment by wagnerdelima** [comment]
Please include your setup here. The configuration you used so I can see them and match against mine.

**Comment by PankajSavaliya** [comment]
Which file configuration do you need? because I have followed your document and it's work fine if user is new or enable from admin. 
just check yourself following this Step: 
1. Create a user by Facebook login.
2. is_active unchecked by manually from the admin panel.
3. then again try to login with Facebook from API (same 1st step) at this step you will get an error.

**Comment by wagnerdelima** [comment]
I just did! This is what I get back in exchange:

```
{
    "error": "invalid_grant",
    "error_description": "User inactive or deleted."
}
```

**Comment by wagnerdelima** [comment]
@PankajSavaliya is your issue resolved?

**Comment by PankajSavaliya** [comment]
Yes, this issue is from my side because I have used custom backend. apologize for taking your precious time. I appreciate your help.
Thanks

**Comment by wagnerdelima** [comment]
No problem at all!
