### ISSUE TITLE
Implement SSO with drf-social-oauth2

### ISSUE THREAD

**Issue by nico-dfg** [wagnerdelima/drf-social-oauth2#19]
Hello everyone,

I am using the library to allow external users to use my django rest framework API.

I would like to register the external user if he is not in the database and connect him if he is.
Is it possible to implement Single Sign On with the library ?

Thank  you in advance for helping me.
Nicolas

**Comment by wagnerdelima** [comment]
You basically would like a single sign on through this framework? Why not just create a SSO on your side of the API? It's easier I would assume.

**Comment by nico-dfg** [comment]
I thought I could use social auth with Open Id connect protocol to implement the SSO.

What do you mean about create the SSO on your side of the API ? 
I should implement a get_or_create function when user is trying to get access token ?

**Comment by wagnerdelima** [comment]
Perhaps I didn't understand your questions. So let's break it down to clarify it. This library offers a way to sign you users in through Facebook (tested personally) and Google (other people tested it and no complains so far). It also offers to connect to any other social api (twitter, instagram, however I never used it with those).

Is that what you are looking for?

**Comment by wagnerdelima** [comment]
@nico-dfg did you see my last message?

**Comment by nico-dfg** [comment]
Yes, I just read it. Thank you very much.
I am going to add SSO on my side and use the library to sign in users.
