### ISSUE TITLE
Apparently any token valid by Google Auth, even if generated by another CLIENT_ID is accepting it, is that correct?

### ISSUE THREAD

**Issue by joaopedroabreuu** [wagnerdelima/drf-social-oauth2#193]
When we logged in using the frontend to get the token from google using a CLIENT_ID, the same used in the backend application, it accepts, which is expected. However, when we made a token request using another CLIENT_ID, which is different from the one on the backend, it also accepts it. This is correct?

**Comment by wagnerdelima** [comment]
Mmm, I am not sure that is an acceptable behaviour. Might be a bug. Let me know if you will investigate it.
