### ISSUE TITLE
[Question] How to use the convert token logic inside Django?

### ISSUE THREAD

**Issue by digoburigo** [wagnerdelima/drf-social-oauth2#212]
I want to convert the token from OAuth to the Django session one, but I need to do it inside Django. How can this be achieved?

Tried to use `requests` and making a POST call internally but it's not working.

**Comment by digoburigo** [comment]
I'm trying to convert the token from the Google OAuth callback, getting the token from the Django session and return to another application. But when I deploy the server, it's not being able to request to itself

```python
def complete_google(request: HttpRequest) -> Response:
    code: str = request.GET.get("code")
    url: str = "https://oauth2.googleapis.com/token"
    payload: Dict[str, str] = {
        "client_id": SOCIAL_AUTH_GOOGLE_OAUTH2_KEY,
        "client_secret": SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET,
        "code": code,
        "redirect_uri": f"{DJANGO_BASE_URL}/complete/google-oauth2/",
        "grant_type": "authorization_code",
    }
    headers: Dict[str, str] = {"Content-Type": "application/x-www-form-urlencoded"}
    response: Response = requests.post(url, headers=headers, data=payload)

    response_json: Dict[str, str] = response.json()
    google_auth_token = response_json.get("access_token")
    url: str = f"{DJANGO_BASE_URL}/auth/convert-token/"
    payload: Dict[str, str] = {
        "grant_type": "convert_token",
        "backend": social,
        "client_id": APPLICATION_CLIENT_ID_GOOGLE,
        "client_secret": APPLICATION_CLIENT_SECRET_GOOGLE,
        "token": google_auth_token,
    }
    headers: Dict[str, str] = {"Content-Type": "application/x-www-form-urlencoded"}
    response: Response = requests.post(url, headers=headers, data=payload)
    return Response(
        response.json(),
     )
```

**Comment by wagnerdelima** [comment]
What is your django base url?

You could do it with self.request.build_absolute_uri('/')[:-1]

Or something like that. 

Finishing the day here. Hope you find it out!

**Comment by wagnerdelima** [comment]
Succeeded?

**Comment by digoburigo** [comment]
No, I'm moving this to a different application, that's going to be in charge of validating the users. So I guess I will not encounter this problem. But if is there a way to make it to call itself would be ideal. Is there any way to call the `view` responsible for converting the token ?

**Comment by dreaquil** [comment]
I believe I managed to do what you were discussing @digoburigo.

class GoogleLoginView(APIView):
    permission_classes = [AllowAny]

    def post(self, request):
        google_token = request.data.get('credential')
        
        if not google_token:
            return Response({'error': 'No Google token provided'}, status=status.HTTP_400_BAD_REQUEST)

        token_exchange_url = request.build_absolute_uri('/auth/convert-token')

        # Perform token exchange with backend OAuth provider
        response = requests.post(token_exchange_url, data={
            'token': google_token,
            'backend': 'google-identity',
            'grant_type': 'convert_token',
            'client_id': settings.GOOGLE_APP_OAUTH2_CLIENT_ID,
            'client_secret': settings.GOOGLE_APP_OAUTH2_CLIENT_SECRET
        })
        
        if response.status_code == 200:
            # Return the access and refresh tokens to the frontend
            return Response(response.json())
        else:
            print(f"Token exchange failed. Status: {response.status_code}, Response: {response.text}")
            return Response({'error': 'Token exchange failed'}, status=status.HTTP_400_BAD_REQUEST)

**Comment by wagnerdelima** [comment]
Careful, you should never return the client secret like that. It should not be exposed for security reasons.
