### ISSUE TITLE
Replace 30 Character Token with JWT for Access & Refresh Token

### ISSUE THREAD

**Issue by mattmillen888** [wagnerdelima/drf-social-oauth2#23]
Could you create the access and refresh tokens as JWT format instead of the standard 30 character token?

I have found this library https://pypi.org/project/python-jwt/ to be excellent on other projects in flask etc as it enables you to create the JWT token in lots of different signing algorithms including PS256.

Is this possible as the project stands is my first question? Secondly if not. How difficult is it to update so it does use the JWT format with this library to generate the access and refresh tokens?

**Comment by alexanderblackh** [comment]
Second this request as well. Seems [](https://github.com/SimpleJWT/django-rest-framework-simplejwt )is one of the common used JWT packages as [](https://github.com/jpadilla/django-rest-framework-jwt) is no longer maintained. One of the competitors to this package, [](https://github.com/st4lk/django-rest-social-auth), supports using SimpleJWT already, but it lacks features like disconnect so I was hoping to switch to this package.

**Comment by wagnerdelima** [comment]
Just acknowledging that I am already implementing the JWT token. I apologise for the delay. Would this help you in any way:

https://jwt.io/#debugger-io?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdG9rZW4iOiJRdTJxaFVkWjFZdE1pZEV2UklTdGE2MVpkRFp6aXgiLCJleHBpcmVzX2luIjozNjAwMCwidG9rZW5fdHlwZSI6IkJlYXJlciIsInNjb3BlIjoicmVhZCB3cml0ZSIsInJlZnJlc2hfdG9rZW4iOiJUTXBIRXJIYUE2cnZVY3JST3BabzN4SnVwbERFQUUifQ.ptHgd-6dLj911zqPsZkqijrNSHjrK2aRMV00PPB4Urk

You'd receive the token and once decoded there would be the same data as before.

**Comment by alexanderblackh** [comment]
That's perfect, thank you very much! Yes, that's the tool I use for decoding JWT's.

**Comment by alexanderblackh** [comment]
@wagnerdelima , any updates on this?

**Comment by wagnerdelima** [comment]
Hi @alexanderblackh.
Sadly no! I did start implementing it however I could not test it yet. I had a job change 2 months ago and that's keeping me real busy. I will keep this thread updated I promise!

**Comment by wagnerdelima** [comment]
@alexanderblackh and @mattmillen888 I just released a new version of the framework. It includes the jwted token. Look for the ACTIVATE_JWT in the readme file. 

Please excuse me delay. Let me know if it helps.
