### ISSUE TITLE
Access convert-token from mobile app

### ISSUE THREAD

**Issue by devaziz0** [wagnerdelima/drf-social-oauth2#25]
I have been using this tool and I find it to be great, I currently use it with a mobile app, I use the convert-token url to get a token and thus give my users access to the API, I just wanted to know if it's a good idea to store the generated client_id and client_secret in the mobile app ?, It seems like a bad practice to me, any suggestions ?

**Comment by wagnerdelima** [comment]
Thanks for using [drf-social-oauth2](https://github.com/wagnerdelima/drf-social-oauth2) framework. No, it's not a good idea (bad practice) to store the client_id and client_secret in your app. Your local storage may be hacked and such tokens retrieved. Store only the access_token in your storage as it has an expiration date.

**Comment by mhoonjeon** [comment]
@wagnerdelima Hi thanks for the information.
I wonder if you're right about not storing the client_id and client_secret in the app/browser, then why do we need to include those two fields(=client_id, client_secret) in the payload to covert-token API endpoint?

Other than storing those two values in the local storage/browser, I don't think there is a way for the client to know those two values, which are needed to get access_token.

Is there a better way or am I missing something here?

**Comment by sumanshusamarora** [comment]
+1 for the question
