### ISSUE TITLE
Google OAuth2 error

### ISSUE THREAD

**Issue by jumcorredorro** [wagnerdelima/drf-social-oauth2#26]
I'm getting this error: "401 Client Error: Unauthorized for url: https://www.googleapis.com/oauth2/v3/userinfo" trying to authenticate a request after generate the token.
I tried everything but I can't figure it out what is happening here.

**Comment by wagnerdelima** [comment]
Can you provide me the stack trace and how to reproduce it?

**Comment by jumcorredorro** [comment]
I understand later that this was my mistake, thanks!

**Comment by wagnerdelima** [comment]
Thank you for opening the issue!
