### ISSUE TITLE
Misleading documentation ? 

### ISSUE THREAD

**Issue by onekiloparsec** [wagnerdelima/drf-social-oauth2#28]
Hi. I've some difficulties following the README and the Social part.

As far as I understand, the first part is for "normal" (non-social) auth. It says one must create an app in the Django admin. There are actually various places, but I firgured out it is in the `Django OAuth Toolkit › Applications` section.

The social part is unclear to me. I managed to make a login through GitHub work, but without any additional application added in the admin (as stated by the README). The ID and Key inside the `settings.py` file were sufficient to achieve the result (as far as I can tell). 

Am I missing something ? Thanks a lot for your help.

**Comment by wagnerdelima** [comment]
Hey. Thanks for opening the issue. You do need to create a `Django OAuth Toolkit › Applications` in order to social auth with GitHub. The Id and Key inside settings.py need to from your github application. They all have to be present in order to make the social auth work.

**Comment by onekiloparsec** [comment]
Thanks for your reply, indeed this is what I managed to understand. 

Yet, the overall workflow is a lot more complicated than I thought. Actually, I didn't managed to make it working. I have an SPA, and the last step when the backend redirects to the SPA, I couldn't managed to transmit an access_code it could use... 

Given the complexity and the diversity of situations, I guess this is hard to document everything.

**Comment by wagnerdelima** [comment]
Did you manage to authenticate using the /conver-token endpoit?

**Comment by onekiloparsec** [comment]
Well, yes. But my main difficulty is to understand how to make a simple "login from GitHub" with a button displayed in the SPA for instance (assuming the OAuth Toolkit Application has been added in the Django admin, of course).

**Comment by wagnerdelima** [comment]
So in this case you would have to fire a request to `/convert-token`. Hence you'd have a response returned to you with the `access_token`. The access token is what grants a user access to a django view. You'd store this access token in the cache/storage of the browser -- depending on your design. Every time you request something from a `/url` you pass the access token to it as a Bearer Token.

This should give you access.

**Comment by onekiloparsec** [comment]
Yes, thanks for the explanation, this I understand. But what about the very first time ? I mean, the user never used the GitHub login/register yet to login into the SPA? You directly make a request to a `/convert-token` or the button shouldn't redfirect to some authorization URL ? In GitHub directly ? Or the one included in `drf-social-auth2` ?

**Comment by wagnerdelima** [comment]
So in this case you would have to fire a request to `/convert-token`. Hence you'd have a response returned to you with the `access_token`. The access token is what grants a user access to a django view. You'd store this access token in the cache/storage of the browser -- depending on your design. Every time you request something from a `/url` you pass the access token to it as a Bearer Token.

This should give you access.

**Comment by wagnerdelima** [comment]
Let me know if it works.

**Comment by wagnerdelima** [comment]
Ah I see. I understood your question now! yes, indeed. You would have to use a third-party library to do that. What is your SPA written with? React, Vue??

**Comment by onekiloparsec** [comment]
Great. :-) Yes, Vue.js

**Comment by wagnerdelima** [comment]
This might help you: https://github.com/dgrubelic/vue-authenticate.

**Comment by wagnerdelima** [comment]
Did you manage this, @onekiloparsec ?

**Comment by onekiloparsec** [comment]
Sorry, I've been pulled out of my standard work by a new job, and couldn't manage yet to check. But it's definitely something I was mistaken about. I knew it exists since long ago, but overlooked at it. I'll close that issue once I managed to make it working, with some comments for those who stumble upon this thread.

**Comment by onekiloparsec** [comment]
It is amazingly difficult, and I still fail to understand what happens. `vue-authenticate` doesn't seem to be a real help sometimes... After hours of trials and errors, I am still unsure if I must config the provider url in `vue-authenticate` config to `auth/login/github/` or `auth/complete/github/`. 

I guess it is the former. But when I make a request on it, CSRF token verification fails. Even if I manually create a backend route to actually get that damn CSRF token, and apply it on the axios request in the SPA.

If I use the latter, there is always a missing `state` parameter, which seems logical, since it is supposed to be produced by the login, right ?...

Thanks for ANY help.

**Comment by wagnerdelima** [comment]
Hi @onekiloparsec. I am sorry for this situation. Please do let me know if I can help in any way?

**Comment by onekiloparsec** [comment]
Thanks for your message. Can you just confirm that a vue-authenticate button (say login with GitHub) on the front-end must point to one of the route opened on Django backend by drf-social-oauth2? And if so, which one?

**Comment by onekiloparsec** [comment]
It seems I finally managed to successfuly get an `access_token` from GitHub using another library though: `django-social-rest-auth`, which doesn't require to create an OAUth2_provider app in the Django admin. I am not sure why, and what consequences it has, but I'll try to move on with that route. Thanks for your help anyway.

**Comment by asencis** [comment]
@onekiloparsec @wagnerdelima Hi Cedric - I'm potentially having similar issues with setting up oauth with ORCID. Do we have to create an application in the admin section for everything to tally up?

**Comment by wagnerdelima** [comment]
You do need to create an application in the admin section!

**Comment by asencis** [comment]
@wagnerdelima Hi Wagner, so just for clarity and using my case (for ORCID) as an example, what would this look like?

**Comment by wagnerdelima** [comment]
@asencis I see you sent me an email. I will reply accordingly. Crazy week here!
