### ISSUE TITLE
Forbidden (CSRF cookie not set.): /auth/authorize

### ISSUE THREAD

**Issue by Kaushal-Dhungel** [wagnerdelima/drf-social-oauth2#30]
I tried to create a new user (sign up) using 
axios.post('http://127.0.0.1:8000/auth/authorize', {
            username: username,
            email: email,
            password1: password1,
            password2: password2,
        })
but I am getting a 403 forbidden error and it says CSRF cookie not set. 
how can I solve this??

**Comment by wagnerdelima** [comment]
In the README file you can read how to SSO. You need to use a Social Account of your choice and use the /convet-token endpoint to authenticate against. Sorry for the late reply.

**Comment by Kaushal-Dhungel** [comment]
I was able to login with Facebook. However, when I tried to create a new user i.e sign up a new user using username, email, password, and confirm password (without using a social account), I was unable to do so. Isn't it possible to create a new user without social authentication using this package?? I want to have multiple options to sign up (using social accounts and also by typing username and password if someone doesn't want to sign up using their social account)
