### ISSUE TITLE
Full implementation example of Social Auth with DRF and ReactJS using this library

### ISSUE THREAD

**Issue by vladkomudrich** [wagnerdelima/drf-social-oauth2#31]
Excellent tool! Continue in the same spirit;) I created [template](https://github.com/vladkomudrich/react-django-socialAuth) of implementation Social Authentication (Google OAuth2 as an example) with Django Rest Framework and React using this library. Anyone can use this👌 

Link: https://github.com/vladkomudrich/react-django-socialAuth

**Comment by wagnerdelima** [comment]
Thank you for creating this issue here. I hope your repo is useful to someone out there! I will close this issue for now just to keep things organised.
