### ISSUE TITLE
Social Auth API testing from mobile

### ISSUE THREAD

**Issue by MUDASSARHASHMI** [wagnerdelima/drf-social-oauth2#32]
I am having hard time to figure out step wise process to test drf-social-oauth2 with Postman. I exposed APIs for my mobile application and I need to signup/register/login users from my mobile using the API.

If someone can help me to figure out workflow step wise for testing on Postman I will be really thankful. 

Cheers.

**Comment by wagnerdelima** [comment]
What have you tried so far?

**Comment by MUDASSARHASHMI** [comment]
Tried to put values mentioned on the main page in Postman. Tried a lot different patterns and can't make mobile app social login API working. 

I just need few basic steps for postman and rest I will figure out myself hopefully.

**Comment by NerdWareTech** [comment]
Actually I really am looking forward for help as I moved form drf-social-auth2 to this repo. Please help me to get facebook users authenticated from my mobile device with social accounts using this library. Thanks
