### ISSUE TITLE
Post Request to /convert-token takes more than 10 second

### ISSUE THREAD

**Issue by ibrahimyaacob92** [wagnerdelima/drf-social-oauth2#33]
This might be a small trivial issue, but it's taking away good end user experience.
it'll be nice to clear it out. Or at least explain what happens in the background.

**Comment by wagnerdelima** [comment]
Hi @ibrahimyaacob92 . Can you provide me with a deeper explanation? I use the framework myself and I never faced such an issue.

**Comment by ibrahimyaacob92** [comment]
@wagnerdelima, firstly, thanks on taking on this project ! It's really helpful. I'm trying to work on some other project using this library. I'll get back to you if i manage to replicate this problem.

**Comment by wagnerdelima** [comment]
Cool, thanks.
