### ISSUE TITLE
Ability to Login with Django Authentication & Social

### ISSUE THREAD

**Issue by ibrahimyaacob92** [wagnerdelima/drf-social-oauth2#34]
If I'm already sign up with email and password, I could not sign in with Google or Facebook. It says email already exist. How to work around this issue ?

**Comment by wagnerdelima** [comment]
The message is consequent of the email being already persisted on your database. You need to add a rule to your code yourself.

**Comment by wagnerdelima** [comment]
@ibrahimyaacob92 did you manage this?
