### ISSUE TITLE
ORCID OAuth /login error: 'social' is not a registered namespace

### ISSUE THREAD

**Issue by asencis** [wagnerdelima/drf-social-oauth2#35]
@wagnerdelima Not sure what I have done wrong here with the setup, but I have tried to use:

```
    path(
        '{}/oauth/'.format(ASENCIS_API_v1),
        include('drf_social_oauth2.urls', namespace='drf')
    ),
    ...
```

and also:

```
    path(
        '{}/oauth2/'.format(ASENCIS_API_v1),
        include('drf_social_oauth2.urls'),
        name='social'
    ),
    ...
```

In my urls.py.

However, I receive the following error:

`django.urls.exceptions.NoReverseMatch: 'social' is not a registered namespace`

I'm trying to begin an OAuth process for the ORCID social backend...

Really not sure what I have done wrong here?

**Comment by asencis** [comment]
@wagnerdelima Are you able to provide any help with this please?

**Comment by wagnerdelima** [comment]
H @asencis .

This is what my urls would look like.

```
urlpatterns = [
    url(r'^auth/', include('drf_social_oauth2.urls', namespace='drf')),
    ...
]
```

The namespace needs to be drf as expected here: https://github.com/wagnerdelima/drf-social-oauth2/blob/872efdc49aaa3e0bf235b6c66bfa2f3151ce055a/drf_social_oauth2/settings.py

Sadly I can't provide you with more info as I can't replicate your issue.
Sorry for the delay.
