### ISSUE TITLE
kwargs['response']['orcid']) KeyError: 'response'

### ISSUE THREAD

**Issue by asencis** [wagnerdelima/drf-social-oauth2#36]
@wagnerdelima I'm trying to integrate this package with the ORCID backend: https://python-social-auth.readthedocs.io/en/latest/backends/orcid.html

However, I'm seeing a number of issues.

When I come to perform a convert-token action, e.g.,

```
curl -X POST -d "grant_type=convert_token&client_id=APP-V6L0CRR65TST7UW1&client_secret=b99946ac-45c0-4c5c-a19e-e0c730e5f109&backend=orcid&token=3bgrab7d-4510-48f4-86c5-76f2f50a6aba" http://0.0.0.0:8000/auth/convert-token
```

I'm seeing the following error:

```
web_1          |   File "/usr/local/lib/python3.8/site-packages/drf_social_oauth2/oauth2_endpoints.py", line 91, in create_token_response
web_1          |     return grant_type_handler.create_token_response(
web_1          |   File "/usr/local/lib/python3.8/site-packages/oauthlib/oauth2/rfc6749/grant_types/refresh_token.py", line 60, in create_token_response
web_1          |     self.validate_token_request(request)
web_1          |   File "/usr/local/lib/python3.8/site-packages/drf_social_oauth2/oauth2_grants.py", line 100, in validate_token_request
web_1          |     user = backend.do_auth(access_token=request.token)
web_1          |   File "/usr/local/lib/python3.8/site-packages/social_core/utils.py", line 251, in wrapper
web_1          |     return func(*args, **kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/social_core/backends/oauth.py", line 410, in do_auth
web_1          |     data = self.user_data(access_token, *args, **kwargs)
web_1          |   File "/usr/src/app/api/authentication/backends/orcid.py", line 66, in user_data
web_1          |     kwargs['response']['orcid']),
```

The error seems to be coming from line 64 of here: https://github.com/python-social-auth/social-core/blob/master/social_core/backends/orcid.py

Any ideas on why this is happening?

**Comment by asencis** [comment]
@wagnerdelima Would it be ok to outline the flow we need, so which endpoints we need to hit and at which points? I am able to get a token back from ORCID - but what do I do with it? How do I create a user off of the back of it? Do you need help documenting the auth flow?

**Comment by asencis** [comment]
@wagnerdelima I've updated my stack trace as it might be more useful. Do you think this could this be an issue with the social-auth-core application?

**Comment by wagnerdelima** [comment]
@asencis managed to fix the issue. The problem lied in the python-social-auth library. Thank you so much for your hard work @asencis.

Here is the PR produced https://github.com/python-social-auth/social-core/pull/554
