### ISSUE TITLE
How many Applications [Oauth Toolkit] are we meant to create?

### ISSUE THREAD

**Issue by AndresJaramillo95** [wagnerdelima/drf-social-oauth2#37]
Greetings!

First, thank you to those who have helped contribute to the repo, It's been an excellent find for my projects. I'm a little confused on how many Applications inside the Django admin page are meant to be created? 

To my understanding, each method of social authentication via Google, Facebook, Twitter, etc... requires a new Application to be made. Based on the three platforms I just stated previous, that would require 3 different applications to be generated through  `Oauth Toolkit` section in Django Admin page.

Is my understanding correct? If not I would greatly appreciate some clarity for the use-case for generating applications with the `Oauth Toolkit`. 

Many thanks! 👍

**Comment by wagnerdelima** [comment]
Hi @AndresJaramillo95.

Yes you need one application created for each type of authentication API you are using. Let me know if I can help in any other way.
