### ISSUE TITLE
How to integrate google authentication?

### ISSUE THREAD

**Issue by PawelRoman** [wagnerdelima/drf-social-oauth2#38]
When adding a new app to google, using google developers console, it makes me generate Oauth2 client ID per platform. 

So for example, android app will have different client ID than ios app. 

But both those apps need to work with the Django REST API I'm working on. And they both need "login with google" feature.

The google config needs just one key, like:

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = 'key goes here'

How do I configure this if I have multiple oauth2 client IDs (one for android, one for ios, etc.)? 

Uploading screen from google dev console to illustrate the issue

![Screenshot at 2021-02-01 19-28-42](https://user-images.githubusercontent.com/8222737/106501886-f4006900-64c3-11eb-85cd-85439fc3434d.png)

**Comment by PawelRoman** [comment]
Problem solved. 

Although google project can have multiple oauth2 client IDs, those client IDs seem to be 'compatible' with each other. Drf social auth backend should use the one with type=Web application. Access tokens aquired using ios or android client IDs key will get verified and converted correctly.

![Screenshot at 2021-02-02 12-59-51](https://user-images.githubusercontent.com/8222737/106597708-0ecfed80-6557-11eb-8333-f1d07f32f06b.png)

**Comment by wagnerdelima** [comment]
Hi @PawelRoman. Thank you for you issue and most importantly your answer. You don't have to specify a platform type as your are authenticating at auth level. 

Good luck.
