### ISSUE TITLE
Network Error when using axios in React Native to call the invalidate-sessions endpoint

### ISSUE THREAD

**Issue by christopher-read** [wagnerdelima/drf-social-oauth2#39]
I'm calling the endpoint from react-native and get the 'Network Error' exception.  

I've traced it down to this line [drf_social_oath2](https://github.com/wagnerdelima/drf-social-oauth2/blob/master/drf_social_oauth2/views.py#L151).  

If I change the Response data from {} to None, this seems to fix the issue. 
In Postman, I don't get an error but I do when running my android app in the simulator.  

The call still invalidates sessions but returns an error and won't run the resolve portion of the Axios call.

**Comment by wagnerdelima** [comment]
Can you post a more descriptive info, logs etc, please? And how to replicate the issue?

**Comment by wagnerdelima** [comment]
@christopher-read did you see the last message?
