### ISSUE TITLE
Additional body parameters for convert-token

### ISSUE THREAD

**Issue by zubrzubr** [wagnerdelima/drf-social-oauth2#41]
Hi Everyone! I'm trying to implement apple id and facebook auth for rest api app. 
My custom user model has two additional fields: birthplace and birthday. I want to populate those fields if facebook or apple auth is succeed, is that possible to pass additional params with convert-token request?

```python
TypeError: create_user() missing 2 required positional arguments: 'birthday' and 'birthplace'
```

It would be also nice to have an option to display proper swagger api call with body example. Thanks

**Comment by zubrzubr** [comment]
I inherit convert token view and add additional scheme to display it in swagger, also I decided to create additional endpoint to populate additional fields

**Comment by wagnerdelima** [comment]
Hi @zubrzubr Sorry for the late message. I've had a crazy nasty week. Yes you did the right thing. The conver-token endpoint connects to other libs/frameworks used by this package. Therefore it might not be a good idea to change it like that.

**Comment by wagnerdelima** [comment]
Almost forgot. Thank you for using this framework!
