### ISSUE TITLE
NoReverseMatch for complete

### ISSUE THREAD

**Issue by zubrzubr** [wagnerdelima/drf-social-oauth2#42]
I successfully got access token using convert-token api point but after looks like I can not use it. It fails during SocialAuthentication runtime when it tries to reverse url pattern:

```python
backend = load_backend(
    strategy, backend, reverse(f'{NAMESPACE}:complete', args=(backend,)),
)
```

Exception:

```python
django.urls.exceptions.NoReverseMatch: Reverse for 'complete' not found. 'complete' is not a valid view function or pattern name.
```

I included urls:

```python
path(f'{API_PREFIX}auth/', include('users.social_urls', namespace='social')),
```

Note, that code in users.social_urls is the same like in library, I just need to inherit some views to specify swagger response and request schemes.
And also I don't have any redirect urls, my flow is:

1. Get facebook token using convert-token api point.
2. Create user
3. Use that token on protected endpoints (permissions.IsAuthenticated)

Does someone has the same issue?

**Comment by zubrzubr** [comment]
The problem was that my custom urls:

```python
path(f'{API_PREFIX}auth/', include('users.social_urls', namespace='social')),
```

and django_social urls from package had the same namespace:

```python
url(f'', include('social_django.urls', namespace='social')),
```

I changed namespace for my project custom urls to 'social_auth' and set setting:

```python
DRFSO2_URL_NAMESPACE = 'social_auth'
```

Issue is resolved, maybe someone will have the same problem as me :)

**Comment by wagnerdelima** [comment]
@zubrzubr thaank you for your time and investigation.

**Comment by scarjkee** [comment]
@zubrzubr Спасибо что разобрался
