### ISSUE TITLE
Revoke Token & Invalidate Sessions Status Code 415?

### ISSUE THREAD

**Issue by asencis** [wagnerdelima/drf-social-oauth2#44]
I'm attempting to POST to the revoke-token endpoint, here is a breakdown of the request headers:

<img width="450" alt="Screenshot 2021-03-11 at 11 40 36" src="https://user-images.githubusercontent.com/70026705/110782130-add6bc00-825e-11eb-9470-a313de9c3072.png">

However, the response is coming back with a status code of 415, with the following details:

```
Unsupported media type "application/json, application/json;charset=utf-8" in request.
```

Could anyone advise why we're seeing these issues for these endpoints? What is the correct content type?

**Comment by wagnerdelima** [comment]
Hi @asencis,

Sorry for the massive delay. Here, I tried it myself on my local environment. Firstly, I created a new token by using hte convert-token endpoint. You can see the token created below:

![image](https://user-images.githubusercontent.com/7796148/147356575-9e3f9ac9-6719-4913-a4d5-e864a675b323.png)

If you go to your admin dashboard you will see the token created:
![image](https://user-images.githubusercontent.com/7796148/147356757-fdc5b891-9f0a-4113-81fa-e05b28ccf642.png)

Copy the newly created access_token.

Byild the request to the new endpoint revoke-token. The Content-Type is just application/json. Once you fire the request you will see the status code is 204.

![image](https://user-images.githubusercontent.com/7796148/147356862-f011e8da-c4da-4cf4-acab-ef0dcf74145d.png)

If you see the dashboard again, there will be no more token there:
![image](https://user-images.githubusercontent.com/7796148/147357039-6b5bc693-e887-40a7-a1dd-ae9abb634d6b.png)
