### ISSUE TITLE
Register New User ?

### ISSUE THREAD

**Issue by ibrahimyaacob92** [wagnerdelima/drf-social-oauth2#45]
Can this library able to register new user ?

**Comment by wagnerdelima** [comment]
Can you be more specific @ibrahimyaacob92 ? What is the problem you're trying to solve??

**Comment by ibrahimyaacob92** [comment]
i want user to be able to register with email and password without gmail or any other socials app

**Comment by wagnerdelima** [comment]
This tool is recommended for social authentication. I wouldn't use for the purposes you are seeking for.
