### ISSUE TITLE
Linkedin cannot convert token

### ISSUE THREAD

**Issue by shukhrat121995** [wagnerdelima/drf-social-oauth2#51]
I was able to receive an authorization_code and convert it to access token. However, when I pass it to http://localhost:8000/auth/convert-token/ I got an error
{
    "error": "invalid_request",
    "error_description": "Backend responded with HTTP403: {\"serviceErrorCode\":100,\"message\":\"Not enough permissions to access: GET /me\",\"status\":403}."
}

I passed as a parameter token, backend - linkedin-oauth2, grant_type: convert_token, client_id and client_secret

**Comment by shukhrat121995** [comment]
I was able to solve it, just need to pass in fronent scope 'r_liteprofile' while getting authentication code

**Comment by Shivam38391** [comment]
`(.env) D:\DjangoProjects\djOauthtest>curl -X POST -d "grant_type=convert_token&client_id=SCezl5G8UNTIBPDiZM6vRKQwM00gFKGvMtWjiH9i&backend=linkedin-openidconnect&token=AQVISd5AITsI-_oBbfWy_yZsxnawJ3YPrLZ9Q91GdjdsQjIZWvx4ReNZWiEIXXCqzJ22Ggn9zVucrxpQmVvagijB3SfDj7npocIOMqm13ys615AjDrjRJ7_H-mP3JTLa4TJwIgr1SH_rHpBh9VvUkNdndu2zvz7dmh4YCQV0iqy8aQTZK9RpHOAhmPYYfp2bzf9M7NbGc3pQvs7M9Yao0dM8v3_GxbLk7iCql8BaZtCdm_NozFSoglkbvNDFWGE65ysD_lew7WXR8R4mwYrTYLvm1AwLkfcV87gWQ4n7rh1PNhbt7EjfxhYFofHvYYLwprCdv66H7am18-XCy33L_1CXe4fTog" http://127.0.0.1:5000/auth/convert-token
{"error":"invalid_client"}`
