### ISSUE TITLE
Azure AD B2C Authentication

### ISSUE THREAD

**Issue by cjd33g8n** [wagnerdelima/drf-social-oauth2#53]
Hey all,

Has anyone successfully authenticated against Azure AD B2C? The social_core module does in fact have a **azuread_b2c**  file, but I cannot seem to figure out how to implement this. Is there any documentation out there on how to set this up? Will gladly put some documentation together if someone can point me in the right direction.

**Comment by wagnerdelima** [comment]
@cjd33g8n did you manage to authenticate with Azure? Thanks.

**Comment by cjd33g8n** [comment]
@wagnerdelima I did manage to successfully authenticate with Azure B2C tenant, however i did not use this package. Ended up having to build custom authentication middleware for my purpose.

**Comment by wagnerdelima** [comment]
@cjd33g8n,

I am sorry you had to go through all that in order to authenticade. I wish I could dedicate more time to the development of drf-social-oauth2. However, so far I am pretty much alone!

Thanks for reporting and all the best.
