### ISSUE TITLE
Change Expiry Time of tokens?

### ISSUE THREAD

**Issue by futurbotconsolidated** [wagnerdelima/drf-social-oauth2#58]
Can anyone help me with this?

**Comment by wagnerdelima** [comment]
You can change the expire date by overwriting the `ACCESS_TOKEN_EXPIRE_SECONDS` like so:


# expires in 6 months
from oauth2_provider import settings as oauth2_settings
oauth2_settings.DEFAULTS['ACCESS_TOKEN_EXPIRE_SECONDS'] = 1.577e7

**Comment by futurbotconsolidated** [comment]
Thanks wagner!
