### ISSUE TITLE
Max retries exceeded with url: /oauth2/v3/userinfo

### ISSUE THREAD

**Issue by samul-1** [wagnerdelima/drf-social-oauth2#59]
I'm experiencing issues on the server-side of my application that are causing all sorts of slowdowns. This is unrelated to Django but, apparently, these issues are also causing logins to fail.

My app uses drf-social-oauth2 to allow users to sign in using their google account. For the past 12 hours, any request made to the endpoing `convert_token` (which always worked fine until today), such as this:

```{"grant_type":"convert_token","client_id":"...","client_secret":"...","backend":"google-oauth2","token":"..."}```

Causes the server to respond after several seconds with:

```
HTTP 400 Bad Request
Allow: POST, OPTIONS
Cache-Control: no-store
Content-Type: application/json
Pragma: no-cache
Vary: Accept

{
    "error": "access_denied",
    "error_description": "Authentication failed: HTTPSConnectionPool(host='www.googleapis.com', port=443): Max retries exceeded with url: /oauth2/v3/userinfo (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f155526e310>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))"
}
```

Like I mentioned, I realize the cause of this is a problem on my end but, is there anything that can be done on drf-social-oauth2 to circumvent this? I read there's an issue with retries, and it makes me think the request ends up timing out or something.

Are there any modifications that can be made to the settings to allow for a looser limit on retries, working around the issue temporarily?

**Comment by wagnerdelima** [comment]
Hi @samul-1,

I apologise for the massive delay. No, there is nothing to be done in the library. The reason you have problems with  max retries is that your API key in google oauth is a test key and google establishes rate limiting. You should check Google's Oauth rate limit prior to sending several requests intermitently. Hope this helps.
