### ISSUE TITLE
auth/token POST request --Invalid credentials given--

### ISSUE THREAD

**Issue by BenK93** [wagnerdelima/drf-social-oauth2#61]
Hey there!
First of all thanks a lot you  have done  wonderful job! 🙏🏽
I'm running to en issue when I try to login  through ` http://127.0.0.1:8000/auth/token` 
I use the exact username and password, client id and secret are copied from admin panel
<img width="745" alt="Screen Shot 2021-06-23 at 15 36 34" src="https://user-images.githubusercontent.com/21170255/123097417-cdbe7400-d438-11eb-83fe-27af44523d79.png">

For example ` http://127.0.0.1:8000/auth/convert-token` works perfectly fine
<img width="777" alt="Screen Shot 2021-06-23 at 15 41 29" src="https://user-images.githubusercontent.com/21170255/123098131-7bca1e00-d439-11eb-99de-eb192d1b30ad.png">

**Comment by visued** [comment]
+1

**Comment by vshia** [comment]
I'm running into the same problem and was wondering if you were able to figure out a workaround (or patch)? Thanks

**Comment by wagnerdelima** [comment]
Hi @BenK93,

I am assuming the convert-token endpoint is not enough for your needs? Did you overcome this issue? 

I am sorry for the delayed response. It's that I've been really busy and I haven't got much help with this repo, so I am all alone to maintain it.

**Comment by Jrad84** [comment]
Hi @wagnerdelima ,

This is an issue for me too.
I am using multiple login schemes so convert-token works well for social auth but I get the same error as the original post on /auth/token endpoint with username & password.

Appreciate your help.

**Comment by wagnerdelima** [comment]
Hi @Jrad84 

Thanks for your message and for your investigation!

**Comment by vishalmehta672** [comment]
> http://127.0.0.1:8000/auth/convert-token

Where we get token?

**Comment by wagnerdelima** [comment]
I suggest you read the README file. It contains information about the endpoint.

**Comment by vishalmehta672** [comment]
I am  use the exact username and password, client id and secret are copied from admin panel.
can please suggest where I am doing mistake.

![Screenshot 2022-01-20 at 5 54 22 PM](https://user-images.githubusercontent.com/53255319/150338600-d995daa4-02e4-4ad4-b4b6-2cb09f8a4e86.png)

**Comment by Shodiev-Shokhrukh** [comment]
+the same

**Comment by wagnerdelima** [comment]
Nowhere in the documentation it suggests the grant_type to be password. Try replacing it by covert_token, instead.
