### ISSUE TITLE
Edit User Model or View for registering

### ISSUE THREAD

**Issue by futurbotconsolidated** [wagnerdelima/drf-social-oauth2#62]
Since Facebook has stopped providing username due to privacy concerns. 
Issue: User created, but Username is some long ID number.

Now I want to edit the register user view so I can create a unique username from views. If anyone can help me in this issue.
<img width="641" alt="Screenshot 2021-06-25 at 15 44 33" src="https://user-images.githubusercontent.com/62669677/123409804-3f7af700-d5cc-11eb-9355-b091120c4460.png">

**Comment by apoorvpandey0** [comment]
Hi @futurbotconsolidated , can you let me know how did you add the provider to your user model?

**Comment by wagnerdelima** [comment]
Hi there, @futurbotconsolidated 

Did you manage to solve this? My late suggestion is: create a django migration and assign a single username to each user.

**Comment by futurbotconsolidated** [comment]
@wagnerdelima I manage to solve this by reusing the pipelines  file of social auth. But can you explain your approach a lil more? Maybe I could use yours.

**Comment by wagnerdelima** [comment]
You are dealing with a database migration, right? You would like to change the data for all users in the database as I understand of course. So you need to create a database migration in your migrations.py file. You would have a function that read the users and assign them a username. Then you would run your migration either manually (I discourage you from that) or automatically, let's say with a deploy. You code you execute once the line in your production pipeline executed the python manage.py migrate

Let me know if I was clear.
