### ISSUE TITLE
 What is <google_token>?

### ISSUE THREAD

**Issue by l25359423** [wagnerdelima/drf-social-oauth2#65]
I registered for google api, but I did not find any information about <google_token>

**Comment by BondarenkoAlexandr** [comment]
I have same question

**Comment by dshwets** [comment]
ha a same question. probably this is token which you will recieve from link like this 

https://accounts.google.com/o/oauth2/v2/auth/oauthchooseaccount?response_type=code&client_id=119059136224-8ejj2i5bg4j2839d5mmm6bl90ah7f4cf.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A8000&scope=openid&flowName=GeneralOAuthFlow

**Comment by wagnerdelima** [comment]
Please check this answer: https://github.com/wagnerdelima/drf-social-oauth2/issues/38. 
Did you resolve this already?
