### ISSUE TITLE
How to configure what fields from the response from social auths are copied to custom user model?

### ISSUE THREAD

**Issue by HarshaSurampudi** [wagnerdelima/drf-social-oauth2#68]
Hi,
I am using google oauth2. I am trying to add 'picture' field to my custom user model when the social user is created. Is it possible by a simple configuration?

**Comment by wagnerdelima** [comment]
You would have to create a picture field in your user model and assign the picture URL google responded with to that picture field. The picture field can be a URL field.

**Comment by XRSIL** [comment]
If you need to specify logic under authorisation, you can add pipeline.py file in your app inside the Django Project, where you will be able to write all the logic you need: create model object, send requests, or anything you want. More in this video: https://www.youtube.com/watch?v=zRrjMJa3N48

As **wagnerdelima** said, you also need to create image filed in your user model.
