### ISSUE TITLE
Google credentials on backend seeming useless

### ISSUE THREAD

**Issue by Irfanwani** [wagnerdelima/drf-social-oauth2#70]
So i was setting google authentication and as per the docs, we need to set 
```
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = <your app id goes here>
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = <your app secret goes here>
```

But even after removing these two settings, there is no change in the app and it works fine. But how??

Also i want to know where i can find full docs about this package like details about urls etc

**Comment by wagnerdelima** [comment]
@Irfanwani would this help you at all: https://github.com/wagnerdelima/drf-social-oauth2/issues/38 ?
