### ISSUE TITLE
Convert google code to tokens directrly.

### ISSUE THREAD

**Issue by dshwets** [wagnerdelima/drf-social-oauth2#72]
Hey, i have a problem in this library with google oauth2. So main question is it possible to convert google code to tokens in this library ? If you will go in google sandbox - https://developers.google.com/oauthplayground/ , there you will chose Google oauth2 API v2, select all,  and click authorize API. firstly u will recive authorization code which u can exchange in tokens. SO is it possible to do in this library - converting Google Authorization code to tokens ? if the answers is YES, then how can do it ?

**Comment by wagnerdelima** [comment]
Hi @dshwets,

I am afraid I didn't understand your question. If you would like to offer your users a mechanism of authenticating to your application by using Google Oauth, yes, you can use this framework. 

You can read about Google instructions in the [README](https://github.com/wagnerdelima/drf-social-oauth2/blob/master/README.rst) file.

All the best.

**Comment by samul-1** [comment]
This is the same use case I'm facing. The convert-token endpoint expects to receive an access_token. However, Google OAuth also has an authorization code flow, in which Google first issues an authorization code, and a server can exchange that code for a pair of access and refresh token. The docstring for ConvertTokenView says:

"
    The endpoint is used in the following flows:

    * Authorization code
    * Client credentials
"

However, I see no way of using it for the authorization code flow. Is there an example on how to implement that flow?
