### ISSUE TITLE
Django > 1.11  URL Path import issues

### ISSUE THREAD

**Issue by chmod77** [wagnerdelima/drf-social-oauth2#76]
Tried this in `Django 4.0b1` and got an error:

`from django.conf.urls import url, include
ImportError: cannot import name 'url' from 'django.conf.urls' (/Users/<>/.local/share/virtualenvs/redacted-api-aqsNCo9p/lib/python3.10/site-packages/django/conf/urls/__init__.py)`

This is due to the changes in the way Django handles URLs now. 

The Django URL module configuration now expects:

`from django.urls import path`

**Comment by chmod77** [comment]
This issue seems to be addressed in the latest release (1.1.2). Closing this now.

**Comment by wagnerdelima** [comment]
Thanks for taking the time and closing this issue.
