### ISSUE TITLE
Google Oauth

### ISSUE THREAD

**Issue by mayankwadhwani** [wagnerdelima/drf-social-oauth2#8]
Hi, 

While using the lib, I am getting this error for Google-Oauth2 

My post request to /convert-token is :
{
  "grant_type": "convert_token",
  "client_id": "django-app-client-id",
  "client_secret": "django-app-client secret",
  "backend": "google-oauth2",
  "token": "facebook-access-token"
}

When making the post request I get the error :

HTTP 400 Bad Request
Allow: POST, OPTIONS
Cache-Control: no-store
Content-Type: application/json
Pragma: no-cache
Vary: Accept

{
    "error": "access_denied",
    "error_description": "Your credentials aren't allowed"
}

**Comment by wagnerdelima** [comment]
Can you give me a more reproducible text/information? What did you do to test?

**Comment by wagnerdelima** [comment]
Any update here?

**Comment by NerdWareTech** [comment]
Wanger did you figured it out? What should be post request supply?

**Comment by Jsalaz1989** [comment]
I've also been having trouble with Google, both with this library as well as [django-rest-framework-social-oauth2](https://github.com/RealmTeam/django-rest-framework-social-oauth2). I always get `{"error":"access_denied","error_description":"Your credentials aren't allowed"}`. I can get it to work with Facebook, but not with Google. I think my configuration of the Django app and the curl parameters are correct, but no luck.
