### ISSUE TITLE
When is it going to be published?

### ISSUE THREAD

**Issue by ZeroCoolHacker** [wagnerdelima/drf-social-oauth2#9]
I would really like to use your fork instead of the original repo. when would it be published and installable via pip?

**Comment by wagnerdelima** [comment]
Hey @ZeroCoolHacker. I think somewhere around Sunday or next week. It's just that I've been working over 16 hours a day cause of a job change! Sorry for this I promise to be quicker on that!! 

Thanks for asking.

**Comment by wagnerdelima** [comment]
@ZeroCoolHacker you may find the package at https://pypi.org/project/drf-social-oauth2/.

Thanks for waiting.
